config/routes.rb
Mtp2::Application.routes.draw do
  root  :to => 'site#index'
  match 'about' => 'site#about'
  match 'terms' => 'site#terms'
  match 'home/dev' => 'site#dev'
  resources :comments
  resources :plans do
    member do
      put 'vote'
      put 'unvote'
      get 'photos', :to => 'plans#photos'
      put 'photo',  :to => 'plans#update_photo'
    end
    resources :destinations, :only => [:new, :create, :edit, :update, :destroy] do
      member do
        put 'position', :action => 'reorder'
      end
      resources :photos, :except => :new
    end
  end
  resources :spots do
    member do
      put 'rate'
    end
    resources :photos, :only => [:index, :show]
  end
  resources :news, :only => [:index, :show]

end

app/views/sidebar/_comments.html.erb
<p class="blockHeader"><img src="/images/side/comment_h.gif" alt="コメント" title="コメント"></p>
<div id="comment">
  <div class="commentSubmit">
  <%- unless logged_in? -%>
    <p class="txtErea"><strong><%= link_to 'ログイン', login_path %> してこのプランにコメントしよう！</strong></p>
  <%- else -%>
    <p class="lead"><%= image_tag '/images/side/comment_txt.gif', :alt=>'コメントを入力して送信！', :title=>'コメントを入力して送信！' %></p>
    <%- comment = @plan.comments.build %>
    <%= form_for comment, :remote => true, :html => {:style => 'margin:0px'} do |f| -%>
      <%= f.hidden_field :commentable_id %>
      <%= f.hidden_field :commentable_type %>
      <p class="txtErea"><%= f.text_area :body, :size => '30x5', :class => 'commentbox' %></p>
      <p class="submitBtn"><%= image_submit_tag '/images/side/comment_sub_btn.gif', :class => 'submit' %></p>
    <%- end -%>
  <%- end -%>
  </div>
  <div id="commentList">
    <%- @plan.comments.limit(5).order('created_at DESC').each do |comment| -%>
      <%= render :partial => 'comment', :locals => {:comment => comment} %>
    <%- end -%>
  </div>
</div>

<script type="text/javascript">
$('#comment form').bind('ajax:before', function(event) {
  $("#comment form input[type='submit'], #comment form input[type='image']").attr({disabled: 'disabled'});
});
$('#comment form').bind('ajax:complete', function(event) {
  $("#comment form input[type='submit'], #comment form input[type='image']").removeAttr('disabled');
});
</script>

app/views/sidebar/_help_edit_plan.html.erb
<div class="blockHeader"><div class="help">プラン編集</div></div>
<div class="help">
  <div class="set clearfix">
    <ol>
      <li>タイトルと概要を入力します</li>
      <li>ステータスを計画中・旅行中・旅行記の中から選択します</li>
      <li>行き先を追加します</li>
      <li>行き先はドラッグアンドドロップで並べ替えられます</li>
      <li>
        それぞれの行き先に関連した写真があれば追加します<br>
        「写真を追加」と書いてある枠にファイルをドロップするとアップロードできます
      </li>
    </ol>
  </div>
</div>

<div class="blockHeader"><div class="help">行き先設定</div></div>
<div class="help">
  <div class="set clearfix">
    <ol>
      <li>場所を検索します</li>
      <li>場所が見つからない場合は「場所を登録」ボタンで新しく追加します</li>
      <li>結果の一覧から場所を選択します</li>
      <li>あれば時間メモとコメントを記入します</li>
    </ol>
  </div>
</div>

<div class="blockHeader"><div class="help">場所登録</div></div>
<div class="help">
  <div class="set clearfix">
    <ol>
      <li>地図上のマーカーをドラッグ&amp;ドロップで目的の場所に移動します</li>
      <li>名前を入力します</li>
      <li>マーカーをドロップした場所の住所が自動入力されるので、確認して修正します。不明な場合は空でも登録できます</li>
      <li>あれば概要を入力します</li>
    </ol>
  </div>
</div>

app/views/sidebar/_help_new_plan.html.erb
<div class="blockHeader"><div class="help">プラン作成</div></div>
<div class="help">
  <div class="set clearfix">
    <ol>
      <li>タイトルと概要を入力します</li>
      <li>ステータスを計画中・旅行中・旅行記の中から選択します</li>
      <li>写真はプラン作成後に設定できます</li>
    </ol>
  </div>
</div>

app/views/sidebar/_hot_users.html.erb
<p class="blockHeader"><img src="/images/side/user_h.gif" alt="いま注目のユーザー" title="ま注目のユーザー"></p>
<div id="user">
  <%- @hot_users.each do |user| -%>
  <div class="set clearfix">
    <p class="icon"><%= image_tag user.profile_image_url, :size => '26x26' %></p>
    <div class="txt"><p><%= user.name %></p></div>
  </div>
  <%- end -%>
</div>
<div class="userLink">
  <%# p class="lineup"><%%= link_to raw('<img src="/images/side/user_btn_off.gif" alt="ユーザー一覧はこちら" title="ユーザー一覧はこちら">'), users_path %%></p %>
</div>

app/views/sidebar/_news.html.erb
<p class="blockHeader"><img src="/images/side/info_h.gif" alt="旅PLuSからのお知らせ" title="旅PLuSからのお知らせ"></p>
<div id="info">
  <%- @news.each do |news| -%>
    <div class="set clearfix">
      <div class="txt"><p><%= news.published_at.strftime('%Y/%m/%d') %><br><%= link_to news.title, news_path(news) %></p></div>
    </div>
  <%- end -%>
</div>

app/views/sidebar/_owners_link.html.erb
<%- if @plan.owner == current_user -%>
<div id="ownersLink">
  <%= link_to image_tag('plan/edit_btn_off.gif'), edit_plan_path(@plan) %>
  <%= link_to image_tag('plan/delete_btn_off.gif'), @plan, :confirm => '本当に削除してよろしいですか？', :method => :delete %>
</div>
<%- end -%>

app/views/sidebar/_tweets.html.erb
<%
=begin
%>
<p><img src="/images/side/tweet_h.gif" alt="01" title="01"></p>
<div id="tweet">
  <div class="set clearfix">
    <p class="icon"><img src="/images/profile/profile_001.jpg"  alt="写真" title="写真"></p>
    <div class="txt"><p><a href="">morimori</a><br>ああああああああああああああああああああああああああああああああああああああああああああああ<br><a href="">http://xxx.com/p/5308916 2010/10/27 10:20</a></p></div>
  </div>
  <div class="set clearfix">
    <p class="icon"><img src="/images/profile/profile_001.jpg"  alt="写真" title="写真"></p>
    <div class="txt"><p><a href="">morimori</a><br>ああああああああああああああああああああああああああああああああああああああああああああああ<br><a href="">http://xxx.com/p/5308916 2010/10/27 10:20</a></p></div>
  </div>
  <div class="set clearfix">
    <p class="icon"><img src="/images/profile/profile_001.jpg"  alt="写真" title="写真"></p>
    <div class="txt"><p><a href="">morimori</a><br>ああああああああああああああああああああああああああああああああああああああああああああああ<br><a href="">http://xxx.com/p/5308916 2010/10/27 10:20</a></p></div>
  </div>
  <div class="set clearfix">
    <p class="icon"><img src="/images/profile/profile_001.jpg"  alt="写真" title="写真"></p>
    <div class="txt"><p><a href="">morimori</a><br>ああああああああああああああああああああああああああああああああああああああああああああああ<br><a href="">http://xxx.com/p/5308916 2010/10/27 10:20</a></p></div>
  </div>
</div>
<div class="tweetLink">
  <p class="logo"><img src="/images/side/tweet_logo.gif" alt="twitter" title="twitter"></p>
  <p class="join"> Join the conversation</p>
</div>
<%
=end
%>

<div id="twitter_widget">
  <%= javascript_include_tag 'http://widgets.twimg.com/j/2/widget.js' %>
  <script type="text/javascript">
  new TWTR.Widget({
    version: 2,
    type: 'search',
    search: <%=raw search_keyword.to_json %>,
    interval: 6000,
    title: '旅PLUS',
    subject: 'みんなのつぶやき',
    width: 247,
    height: 300,
    theme: {
      shell: {
        background: '#8ec1da',
        color: '#ffffff'
      },
      tweets: {
        background: '#ffffff',
        color: '#444444',
        links: '#1985b5'
      }
    },
    features: {
      scrollbar: false,
      loop: true,
      live: true,
      hashtags: true,
      timestamp: true,
      avatars: true,
      toptweets: true,
      behavior: 'default'
    }
  }).render().start();
  </script>
</div>