config/routes.rb
Mtp2::Application.routes.draw do
  root  :to => 'site#index'
  match 'about' => 'site#about'
  match 'terms' => 'site#terms'
  match 'home/dev' => 'site#dev'
  resources :comments
  resources :plans do
    member do
      put 'vote'
      put 'unvote'
      get 'photos', :to => 'plans#photos'
      put 'photo',  :to => 'plans#update_photo'
    end
    resources :destinations, :only => [:new, :create, :edit, :update, :destroy] do
      member do
        put 'position', :action => 'reorder'
      end
      resources :photos, :except => :new
    end
  end
  resources :spots do
    member do
      put 'rate'
    end
    resources :photos, :only => [:index, :show]
  end
  resources :news, :only => [:index, :show]

end

app/models/news.rb
class News < ActiveRecord::Base
  normalize_attribute :title, :with => [:half_width, :strip, :blank]
  normalize_attribute :body,  :with => [:half_width, :strip, :blank]

  validates :title,        :presence => true
  validates :body,         :presence => true
  validates :published_at, :presence => true

  scope :published, lambda{ where('published_at <= ?', Time.now) }
end

app/controllers/admin/news_controller.rb
class Admin::NewsController < Admin::ResourcesController
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  # GET /news
  # GET /news.xml
  def index
    @news = News.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @news }
    end
  end

  # GET /news/1
  # GET /news/1.xml
  def show
    @news = News.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @news }
    end
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/index.html.erb
<div class="footContents">
  <h2 class="title"><img src="/images/news/title.gif" alt="NEWS お知らせ" title="NEWS お知らせ"></h2>
  <ul>
    <% @news.each do |news| %>
      <li><%= news.published_at.strftime('%Y/%m/%d') %> <%= link_to news.title, news_path(news) %></li>
    <% end %>
  </ul>
</div>

app/views/news/show.html.erb
<div class="footContents">
  <h2 class="title"><img src="/images/news/title.gif" alt="NEWS お知らせ" title="NEWS お知らせ"></h2>
  <div id="news">
    <div class="title"><span class="pubdate"><%= @news.published_at.strftime('%Y/%m/%d') %></span> <%= @news.title %></div>
    <div class="body"><%= @news.body %></div>
  </div>
  <div style="text-align: right;"><%= link_to 'お知らせ一覧へ戻る', news_index_path %></div>
</div>