config/routes.rb
Mtp2::Application.routes.draw do
  root  :to => 'site#index'
  match 'about' => 'site#about'
  match 'terms' => 'site#terms'
  match 'home/dev' => 'site#dev'
  resources :comments
  resources :plans do
    member do
      put 'vote'
      put 'unvote'
      get 'photos', :to => 'plans#photos'
      put 'photo',  :to => 'plans#update_photo'
    end
    resources :destinations, :only => [:new, :create, :edit, :update, :destroy] do
      member do
        put 'position', :action => 'reorder'
      end
      resources :photos, :except => :new
    end
  end
  resources :spots do
    member do
      put 'rate'
    end
    resources :photos, :only => [:index, :show]
  end
  resources :news, :only => [:index, :show]

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  
  def index
    @pickup = Plan.pickup
    @news = News.published.limit(3)
    @popular_plans = Plan.popular.limit(4)
    @hot_users = User.popular.limit(10)
  end
  
  def dev
    if logged_in?
      @new_comment = Comment.new(:commentable => current_user)
    end
    @comments = Comment.order('created_at DESC')
  end

end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/site/about.html.erb
<%- content_for :stylesheets do %>
<%= stylesheet_link_tag 'about' %>
<%- end -%>

<h2 class="aboutTitle"><img src="../images/about/title.gif" alt="ABOUT 旅PLuSとは" title="ABOUT 旅PLuSとは"></h2>
<div class="aboutContents">
  <h3 class="lead"><img src="../images/about/lead.gif" alt="旅PLuSはどんなサイト?" title="旅PLuSはどんなサイト?"></h3>
  <p class="plusLogo"><img src="../images/about/plus_logo.gif" alt="PLuS -Planning,Logging,Sharing" title="PLuS -Planning,Logging,Sharing"></p>
  <p class="leadTxt">旅行プランを投稿、閲覧して楽しむことができるサービスです。<br>旅PLuSは、旅行を楽しく便利にすることを目的にしています。<br>旅のプランを探したり、新しくプランを作ったり、自慢したり、楽しみ方は人ぞれぞれです。<br>旅PLuSで良い旅を。 </p>

  <h3 class="pointTitle"><img src="../images/about/title1.gif" alt="POINT1 旅のプランをつくろう" title="POINT1 旅のプランをつくろう"></h3>
  <div class="pointBox clearfix">
    <p class="pointPic"><img src="../images/about/pic1.gif" alt="POINT1 旅のプランをつくろう" title="POINT1 旅のプランをつくろう"></p>
    <p class="pointTxt">旅のプランをつくりましょう。<br>旅PLuSでプランを作ると、旅行の際に最短で回れるコース、みんなに人気のスポットなど、旅行を楽しく便利にする仕組みが盛りだくさんです。<br>こんな旅行をしてみたいという思いをプランにしてください。</p>
  </div>

  <h3 class="pointTitle"><img src="../images/about/title2.gif" alt="POINT2 旅のプランを探そう" title="POINT2 旅のプランを探そう"></h3>
  <div class="pointBox clearfix">
    <p class="pointPic"><img src="../images/about/pic2.gif" alt="POINT2 旅のプランを探そう" title="POINT2 旅のプランを探そう"></p>
    <p class="pointTxt">旅PLuSはみんながつくった旅行プランをみることができます。<br>この場所にいくならこんなプランが人気、こんなスポットがあったなど、お気に入りのプランをみつけてください。</p>
  </div>

  <h3 class="pointTitle"><img src="../images/about/title3.gif" alt="POINT3 旅の思い出を残そう（予定）" title="POINT3 旅の思い出を残そう（予定）"></h3>
  <div class="pointBox clearfix">
    <p class="pointPic"><img src="../images/about/pic3.gif" alt="POINT3 旅の思い出を残そう（予定）" title="POINT3 旅の思い出を残そう（予定）"></p>
    <p class="pointTxt">旅PLuSは自分が行った旅行の記録をつけることができます。<br>旅の思い出を書いたり、行った場所で撮った写真をアップロードしましょう。<br>旅の思い出を残すなら旅PLuSで。</p>
  </div>
</div>

app/views/site/dev.html.erb
<%= render :partial => "comments/new_comment" if @new_comment %>
<%= render :partial => "comments/comments" if @comments %>

app/views/site/index.html.erb
<%- content_for :sidebar do -%>
<%= render '/sidebar', :contents => [:news, :hot_users, {:tweets => {:search_keyword => '#tabiplus'}}] %>
<%- end -%>

<div id="mainArea">
  <h2 class="topH"><img src="/images/top/pic_t.gif" alt="PICK UP ピックアップ" title="PICK UP ピックアップ"></h2>
  <div class="tour">
    <div class="tourInner">
      <div class="tourNameWrapper clearfix">
        <p class="tourName"><%= link_to @pickup.title, plan_path(@pickup) %></p>
        <p class="eval"><img src="/images/plan/face_icon.gif" alt="みんなの評価" title="みんなの評価"></p>
        <p class="evalNum"><%= @pickup.total_votes %>pt</p>
      </div>
      <div class="pickupTour clearfix">
        <div class="leftBox">
          <div class="profile clearfix">
            <p class="photo"><%= image_tag @pickup.owner.profile_image_url, :size => '26x26' %></p>
            <p class="profileName">by <%= @pickup.owner.name %></p>
          </div>
          <p class="photo"><%= plan_photo_list @pickup, :max => 5 %></p>
          <p class="comment"><%= truncate strip_tags(@pickup.outline), :length => 80 %><br><span class="date"><%= @pickup.updated_at.strftime("%Y/%m/%d") %></span></p>
        </div>
        <div class="rightBox"><%= map_image_tag(:longitude => '135.75859870910645', :latitude => '34.98524748805968', :zoom => 14, :size => '400x240') %></div>
      </div>
    </div>
  </div>
  <h2 class="topH"><img src="/images/top/popular_t.gif" alt="POPULAR いま人気のプラン" title="POPULAR いま人気のプラン"></h2>
  <%- unless @popular_plans.blank? -%>
    <%- plan = @popular_plans.first %>
    <%= render 'plans/plan', :plan => plan %>
    <%- if @popular_plans.size > 1 -%>
      <div class="popularS">
        <div class="popularSInner clearfix">
          <%- ['left', 'center', 'right'].each_with_index do |align, index| -%>
            <%- plan = @popular_plans[index + 1] %>
            <%- break unless plan -%>
            <div class="<%= align %>Box">
              <div class="tourNameWrapperS clearfix">
                <p class="tourName"><%= link_to plan.title, plan_path(plan) %></p>
                <div class="evalWrapper clearfix">
                  <p class="eval"><img src="/images/plan/face_icon.gif" alt="みんなの評価" title="みんなの評価"></p>
                  <p class="evalNum"><%= plan.total_votes %>pt</p>
                </div>
              </div>
              <p class="mapSmall"><%=raw plan_map_image_tag plan, '212x127' %></p>
              <div class="profileS clearfix">
                <p class="photo"><%= image_tag plan.owner.profile_image_url, :size => '26x26' %></p>
                <p class="profileName"><%= truncate strip_tags(plan.outline), :length => 20 %>
                  <span class="date"><%= plan.updated_at.strftime("%Y/%m/%d") %></span><br>by <%= plan.owner.name %></p>
              </div>
            </div>
          <%- end -%>
        </div>
      </div>
    <%- end -%>
  <%- end -%>
  <p class="allPopular"><%= link_to raw('<img src="/images/top/all_plan_btn_off.gif" alt="プラン一覧はこちら" title="プラン一覧はこちら">'), plans_path %></p>
</div>

app/views/site/terms.html.erb
<%- content_for :stylesheets do %>
<%= stylesheet_link_tag 'terms' %>
<%- end -%>

<div class="footContents" id="terms">
  <h2 class="title"><img src="/images/rule/title.gif" alt="TERMS OF USE 利用規約" title="TERMS OF USE 利用規約"></h2>
  <div class="txt">
    <h3>はじめに</h3>
    <div class="section">
      この利用規約は株式会社クレイ（以下、「弊社」とします）が、提供する本サービスを利用する全ての行為に適用されます。<br>
      本サービスを利用する全てのユーザーは、本規約に従いサービスを利用するものとします。
    </div>

    <h3>著作権</h3>
    <div class="section">
      本サービス上のすべてのコンテンツに関する著作権は、特段の表示のない限り弊社に帰属しております。これらは著作権法で保護されており、同法により認められている場合を除き、無断で転用、複製等することはできません。<br>
      本サービスを利用し投稿されたツアープランや写真等の情報の権利は、情報を作成したユーザーに帰属します。
    </div>

    <h3>禁止事項</h3>
    <div class="section">
      本サービスを利用するユーザは、以下の行為を行ってはならないものとします。
      <ul>
        <li>弊社または他者を不当に誹謗中傷し、不当な差別を促し、又はその名誉または信用を毀損する行為。</li>
        <li>他者の財産、プライバシー、肖像権、知的財産権の侵害、または侵害する恐れがある行為。</li>
        <li>なりすまし、詐欺、その他あらゆる犯罪に結びつく行為、またはその恐れがある行為。</li>
        <li>弊社または他者のシステムに負荷をかける行為、またはその恐れがある行為。</li>
        <li>あらゆるスパム行為、またはその恐れがある行為。</li>
        <li>その他弊社が不適切と判断する行為。</li>
      </ul>
    </div>

    <h3>免責事項</h3>
    <div class="section">
      <ul>
        <li>弊社は、本サービスに掲載されている内容、またユーザーが本サービスの利用により投稿したいかなる情報について、その正確性、有用性、確実性ほかいかなる保証もするものではありません。</li>
        <li>弊社は、万一ユーザー同士間でトラブルが生じた場合に、ユーザー同士で解決するものとし、一切の責任を負いません。</li>
        <li>弊社は、予告なしに、本サービスの運営を中断または中止、掲載内容を修正、変更、削除する場合がありますが、それらによって生じたいかなる損害についても、一切責任を負いません。</li>
        <li>弊社は、本サービスのご利用により第三者に生じたいかなる損害について一切責任を負いません。システムトラブルやその他予期せぬ要因により障害が生じた場合も同様とします。</li>
        <li>弊社は、本規約その他規約に違反する行為、または違反する恐れがある行為と判断した場合、該当ユーザー情報の削除および、該当情報の削除や変更を行うことがありますが、それにより生じたいかなる損害について一切責任を負いません。</li>
      </ul>
    </div>

    <h3>準拠法</h3>
    <div class="section">
      本サービスのご利用ならびに本利用条件の解釈および適用に関しては、別段の定めがない限り日本法に準拠します。また、本サービスの利用に関するすべての紛争については、別段の定めがない限り東京地方裁判所を第一審の専属管轄裁判所とするものとします。
    </div>
  </div>
</div>