config/routes.rb
Mtp2::Application.routes.draw do
  root  :to => 'site#index'
  match 'about' => 'site#about'
  match 'terms' => 'site#terms'
  match 'home/dev' => 'site#dev'
  resources :comments
  resources :plans do
    member do
      put 'vote'
      put 'unvote'
      get 'photos', :to => 'plans#photos'
      put 'photo',  :to => 'plans#update_photo'
    end
    resources :destinations, :only => [:new, :create, :edit, :update, :destroy] do
      member do
        put 'position', :action => 'reorder'
      end
      resources :photos, :except => :new
    end
  end
  resources :spots do
    member do
      put 'rate'
    end
    resources :photos, :only => [:index, :show]
  end
  resources :news, :only => [:index, :show]

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  
  logic_for_commentable
  logic_for_votable
  logic_for_rankable
  
  Status = [['計画中', 1], ['旅行中', 2], ['旅行記', 3]]

  belongs_to :owner, :class_name => 'User', :foreign_key => 'user_id'
  has_many :destinations, :order => 'position ASC'
  has_many :spots, :through => :destinations
  belongs_to :photo, :class_name => 'SpotPhoto', :foreign_key => 'photo_id'

  def photos
    SpotPhoto.where(:id => DestinationPhoto.where(:destination_id => self.destinations.map(&:id)).map(&:photo_id))
  end

  validates :title, :presence => true
  validates :status, :inclusion => { :in => 1..3 }

  normalize_attribute :title, :with => [:strip, :blank]
  
  scope :popular, order_by_rank

  def self.pickup
    self.find(SiteConfig[:pickup_plan_id].to_i)
  rescue
    self.find(:first, :offset => (self.count * rand).to_i)
  end
  
  def first_spot
    self.destinations.first.spot
  rescue
    nil
  end
  
  def calculate_point(time_range)
    return self.comments.where(:created_at => time_range).count + 
           self.votings.where(:created_at => time_range).count
  end
  
end

# == Schema Information
#
# Table name: plans
#
#  id         :integer         not null, primary key
#  user_id    :integer         not null
#  title      :string(255)     not null
#  status     :integer(1)      not null
#  outline    :text
#  created_at :datetime
#  updated_at :datetime
#  public     :boolean         default(FALSE), not null
#

app/controllers/admin/plans_controller.rb
class Admin::PlansController < Admin::ResourcesController
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_filter :login_required, :except => [:index, :show]
  respond_to :js, :html

  # GET /plans
  # GET /plans.xml
  def index
    @plans = Plan.order('created_at DESC').paginate :page => params[:page], :per_page => SiteConfig[:plans_per_page].to_i

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @plans }
    end
  end

  # GET /plans/1
  # GET /plans/1.xml
  def show
    @map = {}
    @plan = Plan.includes(:spots, :destinations => :photos).find(params[:id])
    @permalink = request.protocol << request.raw_host_with_port << request.fullpath
    @path = []
    @plan.destinations.each do |destination|
      @path << { :latitude => destination.spot.latitude, :longitude => destination.spot.longitude }
    end
    if @plan.destinations.length > 0 then
      @map[:latitude] = @plan.destinations[0].spot.latitude
      @map[:longitude] = @plan.destinations[0].spot.longitude
    end
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @plan }
    end
  end

  # GET /plans/new
  # GET /plans/new.xml
  def new
    @plan = Plan.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @plan }
    end
  end

  # GET /plans/1/edit
  def edit
    @plan = current_user.plans.find(params[:id])
  end

  # POST /plans
  # POST /plans.xml
  def create
    @plan = Plan.new(params[:plan])
    @plan.owner = current_user

    respond_to do |format|
      if @plan.save
        format.html { redirect_to(edit_plan_path(@plan), :notice => 'Plan was successfully created.') }
        format.xml  { render :xml => @plan, :status => :created, :location => @plan }
        format.js
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @plan.errors, :status => :unprocessable_entity }
        format.js   { render :template => '/error.js', :locals => {:title => '作成できませんでした', :message => @plan.errors.full_messages.join("\n"), :script => %q|$("#plan_form input[type='submit'], #plan_form input[type='image']").removeAttr('disabled');|} }
      end
    end
  end

  # PUT /plans/1
  # PUT /plans/1.xml
  def update
    @plan = Plan.find(params[:id])

    respond_to do |format|
      if @plan.update_attributes(params[:plan])
        format.html { redirect_to(@plan, :notice => 'Plan was successfully updated.') }
        format.xml  { head :ok }
        format.js
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @plan.errors, :status => :unprocessable_entity }
        format.js   { render :template => '/error.js', :locals => {:title => '更新できませんでした', :message => @plan.errors.full_messages.join("\n"), :script => nil} }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.xml
  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy

    respond_to do |format|
      format.html { redirect_to(plans_url) }
      format.xml  { head :ok }
    end
  end
  
  # PUT /plans/1/vote
  def vote
    @plan = Plan.find(params[:id])
    @voting = @plan.vote!(current_user)
    respond_with @voting
  end
  
  # PUT /plans/1/vote
  def unvote
    @plan = Plan.find(params[:id])
    @voting = @plan.unvote!(current_user)
    respond_with @voting
  end

  # GET /plans/1/photos
  def photos
    @plan = Plan.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  # PUT /plans/1/photo
  def update_photo
    @plan = Plan.find(params[:id])
    if Plan.includes(:destinations => {:destination_photos => :photo}).where('plans.id = ? AND spot_photos.id = ?', params[:id], params[:plan][:photo_id]).exists?
      @plan.photo_id = params[:plan][:photo_id]
    end
    respond_to do |format|
      if @plan.save
        format.js
      else
        format.js { render :template => '/error.js', :locals => {:title => '写真を更新できませんでした', :message => @plan.errors.full_messages.join("\n"), :script => nil} }
      end
    end
  end
  
end

app/helpers/plans_helper.rb
module PlansHelper
  def plan_status_label(status)
    Plan::Status.rassoc(status).to_a[0]
  end

  def plan_photo_list(plan, opts = {})
    opts = {
      :max => 6,
    }.merge(opts)
    result = ''
    plan.photos.shuffle[0...opts[:max]].each do |photo|
      result << photo_tag(photo.photo, :list, :link_to_original => true)
    end
    raw result
  end

  def plan_map_image_tag(plan, size)
    if plan.first_spot
      opts = {:latitude => plan.first_spot.latitude, :longitude => plan.first_spot.longitude, :zoom => 14}
    else
      opts = {:latitude => Spot::DEFAULT_POSITION[:latitude], :longitude => Spot::DEFAULT_POSITION[:longitude], :zoom => 3}
    end
    link_to map_image_tag(opts.merge(:size => size)), plan_path(plan)
  end
end

app/views/plans/_comment.html.erb
<div class="set clearfix">
  <p class="icon"><%= image_tag comment.commenter.profile_image_url, :width => '24' %></p>
  <div class="txt"><p><%= comment.commenter.name %><br><%= comment.body %></p></div>
</div>

app/views/plans/_destination.html.erb
<div class="editSet">
  <div class="editSetInner clearfix">
    <p class="pic" id="destination_photo_<%= destination.id %>"><%= image_tag !destination.photos.blank? ? destination.photos.first.photo.url(:destination) : image_path('no_image.gif'), :size => SpotPhoto::STYLES[:destination], :class => 'spotPhoto' %></p>
    <p class="txt"><%= destination.time %><br><span class="spotName"><%= destination.spot.name %></span><%= link_to raw('<img src="/images/plan/edit_spot_btn_off.gif" alt="場所を編集" title="場所を編集">'), edit_spot_path(:id => destination.spot_id, :format => :js), :remote => true %><br><%= destination.comment %></p>
    <p class="btn"><%#-
      -%><%= link_to raw('<img src="/images/plan/edit_btn_off.gif" alt="編集" title="編集">'), edit_plan_destination_path(:plan_id => destination.plan_id, :id => destination.id, :format => :js), :remote => true %><%-
      -%><%= link_to raw('<img src="/images/plan/delete_btn_off.gif" alt="削除" title="削除">'), plan_destination_path(:plan_id => destination.plan_id, :id => destination.id, :format => :js), :confirm => '本当に削除してよろしいですか？', :remote => true, :method => :delete %><%-
    -%></p>
    <br clear="both">
    <div class="photo photoList clearfix"><%= destination_photo_list destination, :edit => true %></div>
  </div>
</div>
<div class="edtDirect"><img src="/images/plan/plan_direct.gif" alt="" title=""></div>

app/views/plans/_destinations.html.erb
<ul id="destinations" class="ui-sortable" style="list-style-type: none;">
<%- @plan.destinations.each do |destination| -%>
  <li data-mtp-destination="<%= destination.id %>" data-mtp-spot="<%= destination.spot_id %>" data-mtp-spot-latitude="<%= destination.spot.latitude %>" data-mtp-spot-longitude="<%= destination.spot.longitude %>">
    <%= render 'destination', :destination => destination %>
  </li>
<%- end -%>
</ul>
<script type="text/javascript">
$('#destinations').sortable({
  axis: 'y',
  cursor: 'crosshair',
  update: function(event, ui) {
    var destId = $(ui.item[0]).attr('data-mtp-destination');
    var newPos = $.inArray(ui.item[0], ui.item[0].parentNode.children);
    $.ajax({
      url: '/plans/<%= @plan.id %>/destinations/' + destId + '/position',
      data: {_method: 'put', position: newPos + 1},
      dataType: 'script',
      type: 'POST'
    });
  }
});
</script>

app/views/plans/_form.html.erb
<div id="plantitle<%- if @plan.new_record? -%>Nobg<%- end -%>">
  <div id="plantitleWrapper" class="clearfix">
    <div id="plan_photos_dialog" class="dialog" style="display: none;"></div>
    <%- unless @plan.new_record? -%>
      <div class="editPict" data-mtp-photo-id="<%= @plan.photo_id %>">
        <p class="pict" id="plan_photo"><%= image_tag @plan.photo ? @plan.photo.photo.url(:plan) : image_path('no_image.gif'), :size => SpotPhoto::STYLES[:plan], :class => 'spotPhoto' %></p>
        <%- unless @plan.new_record? -%>
          <p class="select"><%= link_to raw('<img src="/images/plan/select_pic_btn.gif" alt="写真を選ぶ" title="写真を選ぶ">'), photos_plan_path(:id => @plan.id, :format => :js), :remote => true %></p>
        <%- end -%>
      </div>
    <%- end -%>
    <%= form_for @plan, :remote => true do |f| %>
    <div class="editOutline clearfix" id="plan_form">
      <div class="editName clearfix">
        <p class="planNameT"><img src="/images/plan/edit_title.gif" alt="タイトル" title="タイトル"></p>
        <p class="planName"><%= f.text_field :title, :class => 'planNameBox' %></p>
        <p class="status"><%= f.select :status, Plan::Status %></p>
        <p class="statusT"><img src="/images/plan/edit_status.gif" alt="ステータス" title="ステータス"></p>
      </div>
      <p class="outlineT"><img src="/images/plan/edit_outline.gif" alt="概要" title="概要"></p>
      <div class="editComment clearfix">
        <p class="outline">
          <%= f.text_area :outline, :class => 'outline' %>
        </p>
        <p class="saveBtn"><%= image_submit_tag 'plan/edit_save_btn.gif' %></p>
      </div>
    </div>
    <%- end -%>
  </div>
</div>
<script type="text/javascript">
$('#plan_form').parent().bind('ajax:before', function(event) {
  $("#plan_form input[type='submit'], #plan_form input[type='image']").attr({disabled: 'disabled'});
});
</script>

app/views/plans/_plan.html.erb
<div class="tour popular">
  <div class="tourInner">
    <div class="tourNameWrapper clearfix">
      <p class="tourName"><%= link_to plan.title, plan_path(plan) %></p>
      <p class="eval"><img src="/images/plan/face_icon.gif" alt="みんなの評価" title="みんなの評価"></p>
      <p class="evalNum"><%= plan.total_votes %>pt</p>
    </div>
    <div class="pickupTour clearfix">
      <div class="leftBoxPopurar"><%=raw plan_map_image_tag plan, '270x160' %></div>
      <div class="rightBoxPopurar">
        <div class="profile clearfix">
          <p class="photo"><%= image_tag plan.owner.profile_image_url, :size => '26x26' %></p>
          <p class="profileName">by <%= plan.owner.name %></p>
        </div>
        <p class="photo"><%= plan_photo_list plan, :max => 7 %></p>
        <p class="comment"><%= truncate strip_tags(plan.outline), :length => 40 %><br><span class="date"><%= plan.updated_at.strftime("%Y/%m/%d") %></span></p>
      </div>
    </div>
  </div>
</div>

app/views/plans/create.js.erb
location.href = <%=raw edit_plan_path(@plan).to_json %>;

app/views/plans/edit.html.erb
<%- content_for :sidebar do -%>
<%= render '/sidebar', :contents => [:help_edit_plan] %>
<%- end -%>

<div id="mainArea">
  <%= javascript_include_tag 'fileuploader' %>
  <%= render 'form' %>

  <h4 class="scheduleDate">行き先リスト</h4>

  <div class="schedule" id="destination_list">
    <div class="scheduleInnerEdit">
      <div class="routeBtnH"><%= link_to_function raw('<img src="/images/plan/route_btn_off.gif" alt="ルートで地図を見る" title="ルートで地図を見る">'), 'openRouteMap();' %></div>
      <%= render 'destinations' %>
      <div id="destination_form_dialog" class="dialog" style="display: none;"></div>
      <div id="spot_form_dialog" class="dialog" style="display: none;"></div>
      <div class="edtDirect"><%= link_to raw('<img src="/images/plan/add_spot_off.gif" alt="行き先を追加" title="行き先を追加">'), new_plan_destination_path(@plan), :remote => true %></div>
      <div class="routeBtnB"><%= link_to_function raw('<img src="/images/plan/route_btn_off.gif" alt="ルートで地図を見る" title="ルートで地図を見る">'), 'openRouteMap();' %></div>
    </div>
  </div>

  <div id="route_map_dialog" class="dialog" style="display: none;">
    <div class="popInner">
      <div id="routeMap" class="map" style="width: 690px; height: 360px;"></div>
      <div class="photoCtl clearfix">
      <p class="directL"><img src="/images/plan/map_derect_l.gif" alt="前へ" title="前へ"></p>
      <div class="photo">
      <p class="pic"><img src="/images/plan/map_pic.jpg" alt="写真" title="写真"></p>
      <p class="pic"><img src="/images/plan/map_pic.jpg" alt="写真" title="写真"></p>
      <p class="pic"><img src="/images/plan/map_pic.jpg" alt="写真" title="写真"></p>
      <p class="pic"><img src="/images/plan/map_pic.jpg" alt="写真" title="写真"></p>
      <p class="pic"><img src="/images/plan/map_pic.jpg" alt="写真" title="写真"></p>
      <p class="pic"><img src="/images/plan/map_pic.jpg" alt="写真" title="写真"></p>
      <p class="pic"><img src="/images/plan/map_pic.jpg" alt="写真" title="写真"></p>
      <p class="pic"><img src="/images/plan/map_pic.jpg" alt="写真" title="写真"></p>
      <p class="pic"><img src="/images/plan/map_pic.jpg" alt="写真" title="写真"></p>
      <p class="pic"><img src="/images/plan/map_pic.jpg" alt="写真" title="写真"></p>
      <p class="pic"><img src="/images/plan/map_pic.jpg" alt="写真" title="写真"></p>
      <p class="pic"><img src="/images/plan/map_pic.jpg" alt="写真" title="写真"></p>
      <p class="pic"><img src="/images/plan/map_pic.jpg" alt="写真" title="写真"></p>
      </div>
      <p class="directR"><img src="/images/plan/map_derect_r.gif" alt="次へ" title="次へ"></p>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
function openRouteMap() {
  var destinations = $('#destinations > [data-mtp-spot]');
  if (destinations.length < 2) {
    $.gritter.add({title: 'MTP', text: 'ルートを確認するには行き先を 2 ヶ所以上設定する必要があります'});
    return false;
  }
  $('#route_map_dialog').dialog({
    title: 'ルート確認',
    modal: true,
    width: 712,
    height: 474,
    resizable: false,
    closeOnEscape: false,
    open: function() {
      mtp.loadMapWithRoutes('routeMap');
    }
  });
}
</script>

app/views/plans/new.html.erb
<%- content_for :sidebar do -%>
<%= render '/sidebar', :contents => [:help_new_plan] %>
<%- end -%>

<div id="mainArea">
  <%= render 'form' %>
</div>

app/views/plans/photos.js.erb
$('#plan_photos_dialog').dialog({
  title: 'プラン写真選択',
  modal: true,
  width: 712,
  height: 492,
  resizable: false,
  closeOnEscape: false,
  open: function() {
    $('#plan_photos_dialog').html('<%= escape_javascript(render 'photos.html') %>');
    $('#plan_photos').selectable({
      selected: function(event, ui) {
        $('#plan_photo_id').val($(ui.selected).attr('data-mtp-photo-id'));
      }
    });
  }
});

app/views/plans/show.html.erb
<%- content_for :sidebar do -%>
  <%= render '/sidebar', :contents => [:owners_link, :comments, {:tweets => {:search_keyword => @permalink}}] %>
<%- end -%>

<%- content_for :preload_javascripts do -%>
  <%= javascript_include_tag 'jquery.tools.min' %>
<%- end -%>

<%- content_for :image_src do -%>
  <%- if @plan.photo_id %>
    <link rel="image_src" href="<%= @plan.photo.photo.url(:plan) %>">
  <%- end -%>
<%- end -%>

<div id="mainArea">
  <div id="plantitle">
    <div id="plantitleWrapper" class="clearfix">
      <p class="planPic"><%= image_tag @plan.photo ? @plan.photo.photo.url(:plan) : image_path('no_image.gif'), :size => SpotPhoto::STYLES[:plan], :class => 'spotPhoto' %></p>
      <div class="planOutline">
        <div class="planNameWrapper clearfix">
          <div class="planName">
            <h2 class="planNameH"><%= @plan.title %><%- if @plan.status == 1 %><%= image_tag 'plan/icon_under_plan.jpg', :alt => plan_status_label(@plan.status), :title=>plan_status_label(@plan.status) %><%- elsif @plan.status == 2 %><%= image_tag 'plan/icon_under_travel.jpg', :alt => plan_status_label(@plan.status), :title=>plan_status_label(@plan.status) %><%- elsif @plan.status == 3 %><%= image_tag 'plan/icon_memory.jpg', :alt => plan_status_label(@plan.status), :title=>plan_status_label(@plan.status) %><%- end %></h2>
          </div>
          <div class="eval">
            <%= image_tag 'plan/lead_eval.gif', :alt => 'このプランを評価', :title=>'このプランを評価' %><span id='btn-unvote' style='display:none;'><%= link_to image_tag('plan/btn_eval_done.jpg', :alt => 'いいね！'), unvote_plan_path, :remote => true, :method => :put %></span><span id='btn-vote' style='display:none;'><%= link_to image_tag('plan/btn_eval.jpg', :alt => 'いいね！'), vote_plan_path, :remote => true, :method => :put %></span>
          </div>
        </div>
        <div class="icon clearfix">
          <div class="profilePic"><%= image_tag @plan.owner.profile_image_url, :width => 26 %></div>
          <div class="profileName"><%= @plan.owner.name %></div>
          <div class="feed clearfix">
            <p class="face"><%= image_tag 'plan/face_icon.gif', :alt => 'みんなの評価', :title => 'みんなの評価' %></p>
            <p class="faceNum">&nbsp;<span id="totalPoint"><%= @plan.total_votes %></span>pt&nbsp;</p>
            <p class="tweet">
              <a href="http://twitter.com/share" class="twitter-share-button"
                data-count="horizontal" data-text="#tabiplus" data-url="<%= @parmalink %>"
                data-counturl="<%= @parmalink %>"
                data-lang="en">Tweet</a><%= javascript_include_tag 'http://platform.twitter.com/widgets.js' %></script></p>
            <p class="share"><a name="fb_share" type="button" href="http://www.facebook.com/sharer.php?u=<%= url_encode @parmalink %>&t=<%= url_encode @plan.title %>">Share</a><script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share" type="text/javascript"></script></p>
            <p class="like"><iframe src="http://www.facebook.com/plugins/like.php?href=<%= url_encode @parmalink %>&layout=button_count&show_faces=true&width=56&action=like&colorscheme=light&height=18" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:56px; height:23px;" allowTransparency="true"></iframe></p>
          </div>
        </div>
        <div class="comment">
          <div class="commentInner">
            <p><%=raw @plan.outline.escape_html.nl2br %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <h3 class="mapH"><%= image_tag 'plan/couse_t.gif', :alt => 'コースマップ', :title => 'コースマップ' %></h3>
  <div class="planMap clearfix">
    <div id="routeMap" class="map" style="width: 690px; height: 345px;"></div>
    <a class="prev browse left"><%= image_tag 'plan/map_derect_l.gif', :alt => '前へ', :title => '前へ' %></a>
    <div class="scrollable">
      <div class="items">
        <%- @plan.destinations.each do |destination| -%>
          <%- destination.photos.each do |photo| %>
            <div class="pic"><%= photo_tag photo.photo, :list %></div>
          <%- end %>
        <%- end %>
      </div>
    </div>
    <a class="next browse right"><%= image_tag 'plan/map_derect_r.gif', :alt => '次へ', :title => '次へ' %></a>
  </div>
  <h3 class="scheduleH"><%= image_tag 'plan/schedule_t.gif', :alt => 'スケジュール', :title => 'スケジュール' %></h3>
  <h4 class="scheduleDate">行き先 (<%= @plan.destinations.length %>)</h4>
  <div class="schedule" id="destinations">
    <div class="scheduleInner">
      <%- @plan.destinations.each_with_index do |destination, index| -%>
      <div class="planset clearfix" data-mtp-spot="<%= destination.spot_id %>" data-mtp-spot-latitude="<%= destination.spot.latitude %>" data-mtp-spot-longitude="<%= destination.spot.longitude %>">
        <div class="pop"><%= image_tag 'plan/plan_num' + (index+1).to_s + '.gif', :alt => (index+1).to_s, :title => (index+1).to_s %></div>
        <div class="plan">
          <div class="planWrapper clearfix">
            <div class="clearfix">
              <div class="pic"><%= image_tag !destination.photos.blank? ? destination.photos.first.photo.url(:destination) : image_path('no_image.gif'), :size => SpotPhoto::STYLES[:destination], :class => 'spotPhoto' %></div>
              <div class="txt">
                <p class="star"><%- (1..destination.spot.average_rating.to_i).each do |n| -%><%= image_tag 'plan/star_on.gif' %><%- end -%><%- ((destination.spot.average_rating.to_i + 1)..5).each do |n| -%><%= image_tag 'plan/star_no.gif' %><%- end -%></p>
                <p class="detail"><%= destination.time %></p>
                <h5 class="spotName"><%= destination.spot.name %></h5>
              </div>
            </div>

          <div class="txt">
            <p class="mapSmall">
            <%= map_image_tag({
              :latitude => destination.spot.longitude,
              :longitude => destination.spot.latitude,
              :markers => destination.spot.latitude + ',' + destination.spot.longitude,
              :zoom => 14,
              :size => '510x150'}) %>
            </p>
            <table cellspacing="0" cellpadding="0" class="spotDetail">
<%- unless destination.spot.annotation.blank? -%>
              <tr>
                <td><%=raw destination.spot.annotation.escape_html.nl2br %></td>
              </tr>
<%- end -%>
<%- unless destination.comment.blank? -%>
              <tr>
                <td><%=raw destination.comment.escape_html.nl2br %></td>
              </tr>
<%- end -%>
<%- unless destination.photos.empty? -%>
              <tr>
                <td class="photo" style="padding-left:20px; padding-top:14px;"><%= destination_photo_list destination %></td>
              </tr>
<%- end -%>
            </table>
              <div class="spotfeed clearfix">

                <p class="spotEval"><%= image_tag 'plan/spot_eval_t.gif', :alt => 'このスポットを評価する', :title => 'このスポットを評価する' %></p>
                <div class='spotEvalNum' id='star-<%= index %>'>
                <form>
                  <select name='selrate'>
                    <%- (1..5).each do |n| -%>
                      <%- if destination.spot.average_rating.to_i == n -%>
                      <option value='<%= n %>' selected='selected'></option>
                      <%- else -%>
                      <option value='<%= n %>'></option>
                      <%- end -%>
                    <%- end -%>
                  </select>
                </form>
                </div>
              </p>
                <script type='text/javascript'>
                  /**
                   * Ratings
                   */
                  $('#star-<%= index %>').stars({
                    inputType: 'select',
                    cancelShow: false,
                    oneVoteOnly: true,
                    callback: function(ui, type, value) {
                      $.ajax({
                        type: 'POST',
                        url: '<%= rate_spot_path(destination.spot) %>',
                        data: {
                          _method: 'put',
                          score: value
                        },
                        dataType: 'json',
                        complete: function(msg) {
                        }
                      })
                    }
                  });
                </script>
              </div>

            </div>
          </div>
        </div>
      </div>
      <!--planset-->
      <div class="planDirect"><%- if @plan.destinations.size > index + 1 %><%= image_tag 'plan/plan_direct.gif', :alt => '02', :title => '02' %><%- end %></div>
      <script type='text/javascript'>
        /**
         * Ratings
         */
        $('#star-<%= index %>').stars({
          inputType: 'select',
          cancelShow: false,
          oneVoteOnly: true,
          callback: function(ui, type, value) {
            $.ajax({
              type: 'POST',
              url: '<%= rate_spot_path(destination.spot) %>',
              data: {
                _method: 'put',
                score: value
              },
              dataType: 'json',
              complete: function(msg) {
              }
            })
          }
        });
      </script>
    <%- end -%>

    </div>
  </div>
<%#
  <div class="scheduleDateBtn">2010/10/13（水）<img src="../images/plan/date_derect.gif" alt="OPEN" title="OPEN"></div>
   <div class="scheduleDateBtn">2010/10/13（水）<img src="../images/plan/date_derect.gif" alt="OPEN" title="OPEN"></div>
   <div class="scheduleDateBtn">2010/10/13（水）<img src="../images/plan/date_derect.gif" alt="OPEN" title="OPEN"></div>
%>
</div>


<script type="text/javascript">
  $('form#new_comment #comment_submit').attr('disabled','disabled');
  $('form#new_comment #comment_body').keyup(function(event){
    if ($(this).val().length > 0) {
      $('form#new_comment #comment_submit').removeAttr('disabled');
    } else {
      $('form#new_comment #comment_submit').attr('disabled','disabled');
    }
  });
  $('form#new_comment').bind('ajax:success', function(event){
    $('form#new_comment #comment_submit').attr('disabled','disabled');
    $('form#new_comment #comment_body').val('');
  });
  
  function changeTotalVoteView(point){
    $('#totalPoint').text(point);
  }
  
  function onVote(){
    $('#btn-unvote').show();
    $('#btn-vote').hide();
  }
  
  function onUnVote(){
    $('#btn-unvote').hide();
    $('#btn-vote').show();
  }
  
  <%- if @plan.voted_by? current_user -%>
  onVote();
  <%- else -%>
  onUnVote();
  <%- end -%>
  
mtp.loadMapWithRoutes('routeMap');
  $(function() {
    $(".scrollable").scrollable({
      speed: 100,
      onSeek: function() {
        $(window).trigger('scroll');
      }
    });
  });
</script>

app/views/plans/unvote.js.erb
changeTotalVoteView(<%= @plan.total_votes %>);
onUnVote();

app/views/plans/update.js.erb
$.gritter.add({title: 'MTP', text: 'プランを更新しました！'});

app/views/plans/update_photo.js.erb
$.gritter.add({title: 'MTP', text: 'プランの写真を更新しました！'});
$('#plan_photos_dialog').dialog('close');
$('#plan_photo > img').attr({src: '<%= escape_javascript @plan.photo.photo.url(:plan) %>'})

app/views/plans/vote.js.erb
changeTotalVoteView(<%= @plan.total_votes %>);
onVote();